### ISSUE TITLE
No full duplex in Windows

### ISSUE THREAD

**Issue by rubenmedrano** [AuLib/AuLib#2]
Hello

I am trying to capture sound while monitoring but it seems it is not posible in Windows with portaudio ASIO to have more than one only stream. 

I was looking at the source files and you open one stream with SoundIn and another with SoundOut to get in&out sound, but with Windows ASIO it should be done with one only portaudio full-duplex stream. That is a problem. 

Trying the "Using" you post in the readme , it gives SoundOut errors, but if I change the order and I initializate first SounOut and after SoundIn, it gives SoundIn errors, so it should be done at the same time in portaudio, by opening one single full-dúplex stream.

Do you think it could be easily fixed?

I have build some apps with that features, so it is easily posible (I am just a beginner), but I don't know if it would suppose a big change in the library to get that essential feature (and needes to get the full potential of AuLib).

Thanks. 

Ruben Medrano

**Comment by vlazzarini** [comment]
You need to write an IO implementation that suits your needs. It's an issue with Portaudio, not with AuLib,

**Comment by rubenmedrano** [comment]
OK. Thank you.
